sonar.verbose=true
sonar.organization=bhargavorg-key
sonar.projectKey=bhargavorg-key_tracker
sonar.projectName=tracker
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
