sonar.verbose=true

sonar.organization=bhargavorg
sonar.projectKey=bhargavorg_tracker
sonar.projectName=Tracker

sonar.sourceEncoding=UTF-8
sonar.sources=src/main
sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
